title: Marta Mazurkiewicz
site-description: UX Researcher & Psychologist
email: contact@marta-mazurkiewicz.com
description: "UX Researcher & Psychologist"
baseurl: ""
url: "https://marta-mazurkiewicz.com"
email_username: contact@marta-mazurkiewicz.com
medium_username: marta-mazurkiewicz
linkedin_username: marta-mazurkiewicz-434555b7
behance_username: martamazurki
twitter_username:
github_username: mazurki
facebook_username:
your_name: 
copyright_name: Marta Mazurkiewicz
collections:
  tags:
    output: true
    permalink: tags/:path/
# Build settings
markdown: kramdown
paginate: 3 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
