title: Marta Mazurkiewicz
site-description: UX Designer & Psychologist 
email: contact@marta-mazurkiewicz.com
description: "UX Designer & Psychologist"
baseurl: ""
url: "https://marta-mazurkiewicz.com"
email_username: contact@marta-mazurkiewicz.com
medium_username: marta-mazurkiewicz
linkedin_username: marta-mazurkiewicz-434555b7
twitter_username:
github_username: mazurki
facebook_username:
your_name: Marta
about_yourself: >
I'm Marta and I apply psychology to UX. Need a coaching session? Let's talk! 

I have a master's degree in Psychology, I finished Human Resource Management postgraduate studies and I'm a certified coach. I learned design principles and UX in practice working as a UX designer and researcher. It became my passion. 
 
Here, I write about my experience and my perspective on the above issues - UX, design, and coaching. I hope you'll enjoy it. If you need support in achieving your goals, here you can also schedule the coaching session.
 
In my spare time, I do yoga, read books and sometimes draw or create analog collages. I love being in nature but ask me to visit a museum or gallery and I'm yours! Traveling is my second name.
copyright_name: Marta Mazurkiewicz
# Build settings
markdown: kramdown
paginate: 5 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
