title: Marta Mazurkiewicz
site-description: UX Designer & Psychologist
email: contact@marta-mazurkiewicz.com
description: "UX Designer & Psychologist"
baseurl: ""
url: "https://marta-mazurkiewicz.com"
email_username: contact@marta-mazurkiewicz.com
medium_username: marta-mazurkiewicz
linkedin_username: marta-mazurkiewicz-434555b7
twitter_username:
github_username: mazurki
facebook_username:
your_name: Marta
copyright_name: Marta Mazurkiewicz
# Build settings
markdown: kramdown
paginate: 5 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
